In [9]:
import numpy as np
import time

In [10]:
size=1000000

py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"Python last time = {end-start} seconds")

np_arr = np.array (range(size))
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"numpy arr time = {end-start} seconds")

Python last time = 0.0393221378326416 seconds
numpy arr time = 0.0013051033020019531 seconds


In [19]:
arr = np.array([1, 2, 3, 4, 5])
print(arr, type(arr), arr.dtype)

arr2 = np.array([1, 2, 3, 4, 5, "Prime"])
print(arr2, type(arr2), arr2.dtype)

arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr2d , arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' '5' 'Prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)
